# Los siguientes comandos se ejecutan en mysql desde el símbolo del sistema 

SELECT * FROM facturas WHERE FECHA_VENTA='20170101';

-- EXPLAIN FORMAT=JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA='20170101' \G; 

ALTER TABLE facturas ADD INDEX(FECHA_VENTA);

-- EXPLAIN FORMAT=JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA='20170101' \G; 

SELECT * FROM facturas WHERE FECHA_VENTA='20170101';

ALTER TABLE FACTURAS DROP INDEX FECHA_VENTA;

-- EXPLAIN FORMAT=JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA='20170101' \G;